### ISSUE TITLE
Should there be an unfold tactic?

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-redprl#179]
Should RedPRL have a generic unfold tactic, for replacing a custom operator with its definition?

As a simple example, consider the following development.

```
Def MyBool : exp = [ bool ].

Thm MyBoolType : [ MyBool() type ] by [
  auto // works!
].

Thm MyBoolTrue : [ MyBool() true ] by [
  auto; // does nothing because there's no intro rule for MyBool()
  {'tt}; auto // gets stuck because it doesn't unfold/compute in type position
].
```

We can show that `MyBool()` is a type, but not that it is inhabited. This is because `auto` knows to try computation when it sees an `A = B type` goal, but it doesn't compute in the type position when it sees an `a = b in A` goal. 

I suppose we could have `auto` attempt such computation (assuming it is sound) in this specific case. But it might be nice to have a generic unfold tactic.

**Comment by jonsterling** [comment]
Good question; I think we should have an 'unfold' tactic or something analogous, but let me muddy the waters a little with a few remarks:

1. We have followed the advice of Vincent Rahli (who work(s/ed) on Nuprl) and implemented definitional extensions as simply a form of computation rule which is induced by the signature. This is different from some other versions of definitions (like JonPRL's), where only the refiner knows about unfoldings.

2. I think that it should always be safe to unfold a definitional extension, because they are always parametric in their arguments

One thing that we could do as a first cut is have `unfold ϑ in target` as a rule (where `target` is either `concl` or the name of a hypothesis), which then searches the appropriate term for an operator headed by `custom[ϑ]`, and replaces it with the result of computing one step.

**Comment by jonsterling** [comment]
The other question implicit in this ticket is whether we can have a "head expansion" rule that rewrite a goal `A true` to `A' true` when `A :-> A'` in our "cubically-stable stepping judgment". This is a question for @cangiuli.

**Comment by wilcoxjay** [comment]
That all sounds good, thanks! I'll get around to this when I get around to it :)

With respect to the cubically-stable stepping judgment stuff, that's a related but different question, right? If I'm reading your explanation correctly, you're saying that it's always safe to unfold a definition (and this is what the unfold tactic would do). But we could also imagine a more general head-expansion rule that tries to do arbitrary (safe) computation.

**Comment by jonsterling** [comment]
@wilcoxjay Yes, that's right! 👍
