### ISSUE TITLE
Make connections work!

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#209]
It will be great if we can type check this with only `auto`? (Currently RedPRL is quite slow and looks buggy on this, not to mention proving it.)

```
Thm Connection(#A) : [
  a/type : #A type >>
     (a : #A)
  -> (b : #A)
  -> (p : paths({_}.#A; a; b))
  -> paths({i}.(paths({_}.#A; a; p@i)); <_>a; p)
] by [
  {
  lam a. lam b. lam p.
    <i> <j> 'hcom{i=0,i=1,j=0,j=1;0~>1}(#A; ,a;
     {k}.hcom{k=0,k=1;1~>j}(#A; hcom{k=0,k=1;1~>0}(#A; ,p @ k; {_}.,a; {j}.,p @ j); {_}.,a; {_}.,a);
     {k}.hcom{k=0,k=1;1~>j}(#A; ,p @ k; {_}.,a; {j}.,p @ j);
     {k}.hcom{k=0,k=1;1~>i}(#A; hcom{k=0,k=1;1~>0}(#A; ,p @ k; {_}.,a; {i}.,p @ i); {_}.,a; {_}.,a);
     {k}.hcom{k=0,k=1;1~>i}(#A; ,p @ k; {_}.,a; {j}.,p @ j))
  };
].
```

**Comment by jonsterling** [comment]
@favonia I experimented with this and there is just a blowup of proof obligations.

**Comment by jonsterling** [comment]
And there must be some bugs somewhere too, because I am seeing incorrect subgoals arising. It is possible that either the bug is in the rules, or in the refinement apparatus (the latter is probably too complex for you to debug, but I can look into it.)

**Comment by jonsterling** [comment]
I have at least mostly fixed the performance problems which made this kind of impossible to test (the blow-up of subgoals was partially caused by using a "parallel" version of tactic sequencing, in which substitutions don't propagate along the subgoals telescope until after all subgoals have been refined.)

I still get goals now which look either non-trivial or untrue. But at least we can try and figure out what is going on.

**Comment by favonia** [comment]
Fixed a bug in the example. (Finally it's RedPRL helping me debugging.) However there are still four goals left unsolved.

**Comment by jonsterling** [comment]
@favonia Awesome! And once I get around to adding *refinement* rules for compositions (so that you don't have to use `'`/`exact`), it will be easier to write correct compositions anyway.

Regardless, I think that RedPRL *should* (in a moral sense) be able to automatically "typecheck" this example, so we can use it as a target: let's keep fixing things and adding rules if necessary until this example is automatically discharged.

**Comment by favonia** [comment]
@jonsterling You can update the code in OP. I think we really have to solve the naming issues now. We need to find a good name for these rules: @cangiuli

- `p@e = P_e`
- `coe^{r~r}`
- `hcom{r~r}`
- `hcom{r=r}`

The three cases are due to the lack of the symmetry of `CapEq`. Is there a way to sequence two tactics, like `(Symmetry >> CapEq)`? Should we have a special version to handle the cases where both sides are hcom? If so, what should be its name?

**Comment by jonsterling** [comment]
@favonia 

1. OK, I'll address the naming issue prior to merging.
2. There is a way to sequence rules, but let's not do that for now; currently, doing so may cause unexpected behavior with respect to the name store, so I want to keep things as they are for now. I have a plan to address that issue, after which we can remove the "two-step" things and replace them with tactic compositions.

**Comment by cangiuli** [comment]
As I told @favonia today, I don't have any good names for these rules. Proof-theoretically, the first one is a kind of elimination rule: the three hypotheses of path-intro are that you have a path and that its endpoints agree with the type, so the three elimination rules correspond to dimension application and recovering the two endpoints.

The other three equations I currently just refer to as the second, third, and fifth Kan conditions, but you are welcome to make up names.
