### ISSUE TITLE
Compare outputs of RedPRL during testing

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#210]
Compare the output of RedPRL, not just checking success or failure.

**Comment by jonsterling** [comment]
I would recommend strongly against the output of RedPRL at least for now, since that increases to a really high degree the overhead of making significant changes. RedPRL is still in its infancy, and I want it to be able to grow and change as much as possible with as little friction as possible.

There's a dialectic that we have to navigate, between robust testing and agility. I favor agility for now, and I think that we may begin to focus on more robust testing at whichever point RedPRL's design solidifies.
