### ISSUE TITLE
Better syntax highlighting.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#260]
At least in Emacs, I guess.

**Comment by favonia** [comment]
This is partially addressed by #273.

**Comment by favonia** [comment]
Proper syntax highlighting seems to require an almost full parser. One trick example is `,p` where the comma is used in the list of meta variables but also unquoting.

**Comment by jonsterling** [comment]
Yes, I think proper syntax highlighting is impossible, but we can achieve something that is close to good enough. I don't think any editor-mode has proper syntax highlighting except those that delegate to the language itself (like Agda and Idris).

We can also adjust the concrete syntax to make it easier... Let's not worry too much about perfecting this right now, though, since things are bound to continue changing, and we don't want to bury ourselves under tasks that we can't complete on limited engineering 'budget'.

**Comment by favonia** [comment]
Agreed, and the thing I want most is `,p`.

**Comment by favonia** [comment]
Close this issue for being vague. Also this issue has been (partially) addressed.
