### ISSUE TITLE
Labeled record types

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#261]
A sort for labels, and rules and tactics for record types.

**Comment by jonsterling** [comment]
Good, I definitely want to have this too.

**Comment by favonia** [comment]
@jonsterling What is the parameter sort `LBL` used for? I was thinking maybe labels should have the sort `ATOM` or something.

**Comment by jonsterling** [comment]
@favonia That was for when I had started to implement records 😄 (Before RedPRL switched to CHiTT)

**Comment by jonsterling** [comment]
feel free to use whatever names you think are best though!

**Comment by favonia** [comment]
@jonsterling It is for crazy polymorphism we could probably have in the future... when atoms can be reasoned with in some fancy way. Maybe we should stick with `LBL` for the moment.

**Comment by favonia** [comment]
I realized in an untyped setting this can be done in millions of different ways. Maybe a value in a record is just a list? Or we have a special record constructor with possibly duplicate labels as parameters (and only the expression corresponding to the first occurrence of the label will be used)? @jonsterling I wonder which one is your favorite?

**Comment by jonsterling** [comment]
This is a great question; in Nuprl, records are "functions" from `Atom` to whatever... In practice, the proof obligations that arise for well-typedness are fairly difficult and hard to automate.

One option which is maybe a bit more tractable is to have records formed like with `nil` and `cons[lbl](term; record)` as constructors, and as you suggest, have the projections target the first occurrence of `lbl`. Then in the type system, records ought to be regarded extensionally and negatively.

I think it's also pretty important for automation / type "checking" that the labels be static, rather than internalized through a type of atoms, like in Nuprl.

**Comment by favonia** [comment]
My other idea is to have a "tuple" operator which takes a list of parameters, and the arity is the length of the parameter list. Do you prefer the nested version more than the flat version? (And I guess we don't want fancy record polymorphism (yet).)

**Comment by jonsterling** [comment]
@favonia Your tuple idea sounds very nice too, and it might be easier to type"check"; we can still make it extensible with another operator, so that's fine :)

**Comment by favonia** [comment]
@jonsterling Now I am thinking whether a pair should be a tuple with labels "1" and "2".
