### ISSUE TITLE
A more powerful `use` tactic.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#322]
I think RedPRL should try to solve these, in addition to direct match:
- common subtyping (nat -> int, bool -> weak bool)
- subkinding
- internalized equality to equality and vice versa

Moreover, it can also try to solve these:
- true judgments to type judgments
- true judgments to synth judgments (not sure if we should use the type or the term part...)
- eq judgments to synth judgments (not sure if we should use the type or the term part...)
- type judgments to synth judgments
- (internalized) equality to type judgments
- path to (internalized) equality with a discreteness subgoal
- (more?)

The question is, what should go into the feature list?

**Comment by jonsterling** [comment]
I agree with you about those first three, that would be nice! As for the other judgments, many of those could be cool too... I probably wouldn't worry too much about the synth judgments for now, but otherwise that seems like a very nice list of features.

We shouldn't feel pressure to get all of this done immediately, but as time passes, these would all be welcome additions.

**Comment by favonia** [comment]
@jonsterling Do you like proving `x : y type >> y type` by just `use x`?

**Comment by jonsterling** [comment]
@favonia Yes, I would like that to work if possible.
