### ISSUE TITLE
Avoid invoking rules that obviously require further user inputs in the `auto` tactic.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#333]

**Comment by favonia** [comment]
29547690a56f4ed48598e5ff1eba1ed287cee2dd is not good enough. In the cases `APP` and `PATH_APP`, only when we can easily synthesize the function types or the path types should `dfun/eq/app` or `path/eq/app` be used.

**Comment by jonsterling** [comment]
@favonia This feels like a different kind of case though... The task of synthesizing the type of some program (`SYNTH R`) is well-defined even if out-of-context: so if `auto` gets stuck and the user has to provide an explicit type there, then that is maybe not so bad. Whereas for things like positive elim rules, the goal that is generated is just something like `TERM EXP` or whatever, and we need to ensure that `auto` never generates subgoals like this, since you really can't guess what to do with that.

Does what I'm saying make any sense? I'm sorry that I'm not phrasing it very clearly.

**Comment by favonia** [comment]
Hmm maybe after #359 it would be more manageable. Right now it is often the case that I have to come up with some type for a gigantic term, and those terms heavily use `void/elim` which gives no type information at all.

**Comment by jonsterling** [comment]
@favonia Ah, I see! Interesting.

In Nuprl, by the way, they actually attach type annotations internally to subterms and these help drive things like inference heuristics. I'd like to avoid this as much as possible, but something along those lines may become necessary ultimately. It's hard to tell.

**Comment by jonsterling** [comment]
I agree that it seems like if we implement the granular unfolding rules that you suggested, we can avoid some of this problem... Usually if you have to prove some typing lemma about a very big term all at once, it means that things were unfolded too early.

**Comment by favonia** [comment]
Hmm this is still not good enough unless we support very fancy fixed point unfolding like this
```
  ($ Plus (S n) m) ~~> (succ ($ Plus n m))
```
unlike the current unfolding
```
  ($ Plus (S n) m) ~~> ($ (........very long code......) n m)
```
where you might have to prove well-formed over and over again. Before we have this fancy unfolding, the reason to hold `fun/app` and/or `path/app` is that we can infer more info from `TRUE` or `EQ` judgments than that from `SYNTH` ones. It seems easier to write a tactic in the user land to discharge the non-dependent cases.

**Comment by jonsterling** [comment]
@favonia Indeed; This is something that you would probably need to just prove as a lemma.
