### ISSUE TITLE
Questions about universe levels

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#341]
Why do we have the ability to take lubs of two levels, and also `labove i`? When you have cumulativity, in practice there is no need to ever take the lub of two levels, and even allowing this makes things very difficult (i.e. leads to hard subgoals, and the need for some kind of constraint solver probably, for things to be usable).

In a Nuprl-style proof system with explicit level polymorphism **and cumulativity**, you basically only ever need `lsuc` in practice. Keeping things simple like that makes your wellformedness subgoals generally easier to deal with. So, I was curious what was insufficient about the design I proposed with only `lsuc`, `lzero` and variables `i`, which led to the introduction of the more sophisticated system.

For instance, I tried to prove that the type of categories at universe level `i` was a type (given using a dependent record type and universes), and the subgoals I got looked quite difficult, and unlikely to be resolved through automation without much more sophisticated level solving apparatus. Maybe I misread it though.

**Comment by favonia** [comment]
The lub is for
```
A type at i, B type at j >> (-> A B) type at (lmax i j)
```
What's the proposed level for `(-> A B)` in your system without changing the hypotheses? The `labove` and numbers do not add any ability beyond `lzero` and `lsuc` but just use inf-nary numbers instead of unary numbers; `{labove x 0}` is equivalent to `x`, `{labove x}` is `{lsuc x}` (not "anything beyond `x`") and `{labove x 3}` is `lsuc {lsuc {lsuc x}}}`, `3` is `{lsuc {lsuc {lsuc lzero}}}`. So, I believe nothing is made more difficult, but maybe the name `labove` should be changed.

The reason to use inf-nary numbers instead of unary numbers is efficiency---the internal, normalized levels for the inequality solver is in inf-nary forms. Also I think it's easier for the user to write just `3`. By the way, `lmax` is also generalized to take arbitrary numbers of arguments.

**Comment by jonsterling** [comment]
@favonia In practice, you actually never need to compare universe levels that are based at a different level variable: what I mean is, whilst it's possible to talk about `i, j`, in practice, you are only ever really going to have a single variable `i` that is active.

Now, I understand that with how things have been designed, that invariant probably *won't* hold. But having to reason about multiple level hierarchies is a disaster for automation in practice, and is one of the reasons that level polymorphism is unusable in Agda.

**Comment by jonsterling** [comment]
For instance, in Nuprl, you actually only ever parameterize by one level variable `i`, and everything is of the form `suc^n(i)`. This makes things quite easy to deal with... I'm not saying we have to switch to that, since I don't know how to integrate that with your design for the judgments. But I am suggesting that it's probably going to be really difficult to get a base level of usability for the approach that uses `lmax` everywhere, unless I'm misunderstanding how things work.

**Comment by jonsterling** [comment]
To be concrete, the rule for function types is the following under the *cumulative* hierarchy regime:

```
A type at i
B type at i
-----------------
(-> A B) type at i
```

If `A type at j` and `j != i`, you will end up inducing an obligation to show that `j <= i`; so, I think you don't lose anything. But the point of this is to allow information to flow in the right direction for proof refinement.

In the rules for type theory, `lmax` should only ever be surfaced in a non-cumulative level regime.

**Comment by jonsterling** [comment]
(Thing like `lmax` can be useful too if you are trying to do typical ambiguity / universe level synthesis for unannotated code. But we're not doing that in RedPRL.)

**Comment by favonia** [comment]
The `lmax` you saw might be just some artifact and this reminds me of another unimplemented optimization in the pretty printer. For example, `labove x` is probably shown as `max(1, x + 1)` because of a the sub-pretty printer, but it's of course equivalent to `x + 1`. Could you show some examples in your developments that surprised you?

**Comment by jonsterling** [comment]
@favonia Sure, I will post some examples later today. Though, ultimately, I think that regardless of the examples, the design principles of how to integrate level polymorphism with cumulativity still hold, and we might be doing it wrong if we are doing rules like `A type at i, B type at j >> (-> A B) type at (lmax i j)` (which ought to be derivable in any case, but doesn't belong as a rule in the cumulative version of type theory).

**Comment by favonia** [comment]
> To be concrete, the rule for function types is the following under the cumulative hierarchy regime:
> 
> A type at i
> B type at i
> (-> A B) type at i

I am confused. This is how currently the rules work due to the lack of level synthesis, and the inequality solver handles the `i <= j` obligations. What exactly is the surprising behavior you saw?

**Comment by jonsterling** [comment]
@favonia Oh, it sounds like I might be the confused one 😄 Let me investigate and get back to you.

**Comment by jonsterling** [comment]
I'm going to close this because the I think the questions I asked aren't the same as the questions which I need to ask.
