### ISSUE TITLE
Auto-internalize a goal which is `EQ_TYPE` involving neutral terms.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#361]

**Comment by jonsterling** [comment]
This seems like a really good idea.

**Comment by favonia** [comment]
Hmm this has to be done with subtyping (`nat` -> `int`, `(U k l)` -> `(U k' l')`, ...).

**Comment by favonia** [comment]
Waiting for #364.

**Comment by favonia** [comment]
Another way to address this: have `EqTypeApp`, `EqTypeProj`, `EqTypeElim`, ... and a new categorical judgment `SUB_UNIVERSE` such that `SUB_UNIVERSE ((U 1 kan), (2, hcom))` is provable

**Comment by jonsterling** [comment]
@favonia Indeed; those rules seem in some sense perhaps more principled, but it might be harder in the long run because of the blow-up in the number of rules we need to provide. I would prefer if we can find a way to make this work through the universes, but I defer to your judgment.

As for a sub-universe judgment, I would prefer to use general subtyping.

**Comment by favonia** [comment]
@jonsterling Yeah... I do not mind copying and pasting for now. One benefit of having a sub-universe judgment is that we can delay the universe level assignment (as in #351) till the end of the world.
