### ISSUE TITLE
Use `abs x. tactic` instead of `<x> tac`.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#422]
I think it is more uniform to have
```
lam x.
let x = ....
abs x.
```
to introduce bindings. Thoughts?

**Comment by jonsterling** [comment]
@favonia I think this makes sense! I agree.

**Comment by jonsterling** [comment]
@favonia I was thinking about this in the morning, and while I like using `abs x. tac` because it is a lot more consistent, I am a bit unsure about using `<...>` for tuples; we used to use this notation, and I found it kind of hard to read.

I don't feel strongly about it, though, so I leave the final decision to you.
