### ISSUE TITLE
Allow "eta-reducing" sides of hcom

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/sml-redprl#447]
It seems that very often, tube sides of an hcom are exactly paths that we have lying around somewhere. Can we add syntactic sugar so that if a tube side `p` doesn't have a binder, we automatically "eta-expand" it to `[x] (@ p x)`?

For example, instead of:
```
`(hcom 0~>1 ty a [i=0 [j] (@ p j)] [i=1 [_] a])
```
just write:
```
`(hcom 0~>1 ty a [i=0 p] [i=1 [_] a])
```
Or is this a bad idea for some reason? I'm not suggesting that we replace the tubes with elements of line types, but simply that we add this to the parser.

**Comment by jonsterling** [comment]
I was thinking about this some more, and one problem with this idea is that it introduces an inconsistency.

First, note that *all* arguments are binders; just some of them are nullary binders. Next, note that the syntax for a nullary binder is just a term. (That is why you can write `(Foo m)` rather than `(Foo [] m)`.

So, it is already possible to write `[i = 0 p]` in a tube, and this has a meaning that you are not expecting: namely, `[i=0 [_] p]`.

I'm not sure how to achieve the shorthand you want without making a confusing inconsistency...

**Comment by cangiuli** [comment]
I see; I didn't realize that. Then I think there are three ways forward:

1. Do nothing.
2. In the proof theory, have `hcom`s take elements of line types as arguments, with subgoals like `(= ty/a (@ tube r) cap)`.
3. In the proof theory, have `hcom`s take elements of _extension types_ as arguments, so that the above subgoals are enforced by types. (These are like path types, except with arbitrary `r = r'` sides rather than only `x = 0, x = 1`.)

I haven't tried writing down the semantics for (3), so we wouldn't be able to enact this immediately, but at first blush I don't see any issues with these being pretypes at the very least. Thoughts? @favonia @mortberg

**Comment by cangiuli** [comment]
Maybe this is obvious, but I'll point out that we don't want the tube sides to be elements of _path types_, because `hcom` frequently does not constrain one or both `y`-sides of the tube, unlike in the CCHM theory.

**Comment by favonia** [comment]
For 2, I suppose what's written as `[r=s [x] p]` now must be changed to `[r=s (abs [x] p)]`, right?

**Comment by cangiuli** [comment]
Yes; for either (2) or (3). Unless you can think of a way to have it both ways.

**Comment by jonsterling** [comment]
Honestly I really think that (1) is our best option. I suspect that other options would lead to a lot of complexity in the proof theory, since you have to apply rules to even recognize that `(abs [x] base) @ 0` is the same as `base`. The benefit of (1) is that we have a lot of equations that hold up to alpha equivalence, rather than (2,3) where they hold only up to computational or judgmental equality (which is not for free).

**Comment by favonia** [comment]
Alright, but it is `wont-fix-forever`.
