### ISSUE TITLE
Claims that can be unfolded

### ISSUE THREAD

**Issue by cangiuli** [RedPRL/sml-redprl#479]
I would love to have `claim`s whose definition can be unfolded. Ideally the unfolding would be an untyped rewrite. This would reduce code duplication.

A frequent use case would be constructing a filler as an element of a line type and then using both the filer and its composite. Is there a way to do this where all the adjacencies won't get checked twice?

**Comment by cangiuli** [comment]
Does it being a hypothesis mean that `x ~ y` has to be a pretype? That's the only part I'm a little concerned about.

**Comment by jonsterling** [comment]
@cangiuli I think it does not mean that `x~y` has to be a pretype, since we wouldn't be internalizing it (it would just be an atomic form of judgment). But since we aren't imposing any rules for it except those which deal with `\delta`-equality, surely it could be modeled in its proposed form as a pretype for now (?), even if we don't want to consider it as such.

**Comment by cangiuli** [comment]
Well, I'm not sure what functionality obligations it has in RedPRL?

**Comment by cangiuli** [comment]
Let me elaborate about my concern. Say that I make a `claim` that results in hypotheses `x : A, p : x ~ #1`. Can I cut the `x : A` hypothesis with a term of type `A`? What can the resulting `p` possibly mean?

**Comment by jonsterling** [comment]
I see what you mean! Let me think about it a bit.

**Comment by jonsterling** [comment]
After thinking about it a bit, I believe that you are right that functionality scuttles this.

(I think your example doesn't quite work, because when we say that "`claim` results in hypotheses `x:A,p:x~#`", we are talking about a *premise*, not a conclusion. It's easy to get confused about this, since in a proof assistant we are working from conclusions to premises, whereas on paper we combine premises to get conclusions).

Functionality does indeed break this idea, however: this judgment is of course not stable under typed substitutions. In fact, we had a bug in JonPRL toward the very beginning that relied on this kind of mistake; it was easy to prove false...

So, to conclude, I think we cannot use an untyped judgment like this. It seems like it is necessary to introduce a *typed* equation, and incur the cost of rewriting, unless anyone has a better idea.

**Comment by cangiuli** [comment]
Top-level definitions already allow for untyped unfolding operations; is there a reason we can't just have a local version of that? (These would be unfolded in the extract, but not unfolded in the proof unless a tactic does so.)

> _typed_ equation

So, singleton types? My only concern is that I want to avoid repeatedly re-checking the claimed term in to satisfy well-formedness conditions. (If I claim `x := M : A` then when I get `x : S_A(M)` I don't want to recheck that `M : A` ever again.)

**Comment by cangiuli** [comment]
Does having `let` as a construct in the programming language help in any way? (If we extract "local definitions" that way then it could at least avoid code duplication in the extract.)

**Comment by jonsterling** [comment]
@cangiuli 

> Top-level definitions already allow for untyped unfolding operations; is there a reason we can't just have a local version of that? 

The problem is, how do you know what to unfold something to? Top-level definitions are part of the signature, which contains operators together with their unfoldings; the signature is a completely different structure from the context. In the context we have judgments like `A true, M = N : A`, etc. When you `claim` something, it introduces an assumption like `x : A true`. What do you suggest we put here?

> So, singleton types? My only concern is that I want to avoid repeatedly re-checking the claimed term in to satisfy well-formedness conditions.

Indeed, that is precisely the disadvantage of the typed equation. I don't know how to get around it...

> Does having let as a construct in the programming language help in any way? 

I think that this doesn't help.

**Comment by favonia** [comment]
Perhaps we can have local definitions/theorems which extend the signature in that scope, then?

**Comment by jonsterling** [comment]
I want the rules to be as modular as possible from the signature, since I don’t like how the signature works right now. So, I want to rule out that solution (which involves making the signature part of the sequent) and find something better.

**Comment by favonia** [comment]
As a workaround, how about making `claim` take an optional hypothesis name for the additional judgment `x = something in blah` in case that the `claim` is for `TRUE`?
