### ISSUE TITLE
for PRs, allow only squash or rebase, and demand testing to be passed?

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#587]
Now GitHub provides fine-grained controls over the operations available to PRs.... @jonsterling

**Comment by cangiuli** [comment]
Sure, that seems reasonable!

**Comment by jonsterling** [comment]
I've switched it so that you can only do squash or rebase; do you know how to make it so that tests have to pass?

**Comment by favonia** [comment]
https://help.github.com/articles/enabling-required-status-checks/

**Comment by favonia** [comment]
We can even demand reviews if we want to.

**Comment by jonsterling** [comment]
I've turned on basically the most draconian set of restrictions for `master` so we can try them out 😄 If it seems too much, we can make adjustments. I made it so that reviews are required, tests passing are required, and I think I made it so that we can't even push directly to `master` without going through a PR (I hope that's what this setting did, not sure--we'll find out).

**Comment by favonia** [comment]
Closed as fulfilled.

**Comment by favonia** [comment]
@jonsterling I think you are the only one who can merge PRs now.

**Comment by jonsterling** [comment]
oh no!! I guess I messed up the settings... let me fix it when i get back to a computer

**Comment by jonsterling** [comment]
I think I have fixed it.
