### ISSUE TITLE
Set up CONTRIBUTING and solve (most) legal issues at once

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-redprl#626]
@jonsterling I am trying to strike a balance between legal perfection and zero bureaucracy. How about a CONTRIBUTING file mentioning the copyright assignment? This means:

- [ ] Create CONTRIBUTING to make clear about copyright assignment and technical guildlines
- [ ] Enable https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by jonsterling** [comment]
Sure. To be honest, I don't think this is necessary at all (since there is no possible future in which we would expect to encounter legal issues, even if there is technically a possibility)---but I have no problem with it, and support your initiative!

A `CONTRIBUTING` document sounds like a reasonable thing to have regardless, so I support it.
