### ISSUE TITLE
Switch to left-wing license

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-redprl#93]
At this point, I'm not sure there's much point in continuing to use the MIT license; I have always used it for everything since I was used to doing industrial open-source, but I think that our values would be better served by using a left-wing license, such as some variant of GPL.

Does anyone have any thoughts or suggestions?

@RedPRL/politburo @david-christiansen

**Comment by freebroccolo** [comment]
If it were up to me I would not use the GPL. In my experience, it does not provide any practical benefits and instead just creates a number of headaches for other projects. This is particularly evident with the split in the community caused by the GPL 3.

At this point, it's mostly core GNU projects using the GPL 3 and many of them are slowly but steadily losing people for a number of reasons (e.g., see recent threads on the emacs mailing list). I think the GPL 3 has done far more harm than good for both Emacs and GCC. The fact that Linux will probably never move to GPL 3 says a lot.

I'm sympathetic to the ideas behind the GPL and I used to be very strongly in favor of it a decade ago. However, I don't think the principles behind it are very well reflected in the various GNU projects as they currently stand. Maybe I just don't get it though. I'm more interested in creating things with other people than I am in telling them they have to use something a certain way or that they can't have a particular feature (e.g., convenient access to GCC internals) because that might make things too open.

Anyway, that's just my opinion. I don't feel all that strongly about it either way. If you think there's a compelling case for it, I'm okay with that.

**Comment by diakopter** [comment]
You guys. I seriously can't tell whether or not this is satire... I kind of hope it's satire, because left-wing values?

**Comment by jonsterling** [comment]
@diakopter: This is off topic; this thread is for discussion of licenses. I want to make clear, no decision has been made, and I am interested in feedback from people who have used copyleft licenses before—negative feedback is especially welcome.

**Comment by david-christiansen** [comment]
I don't think GPL is any more or less left-wing than the MIT license.

I'm not really a stakeholder in RedPRL, given that I'm neither a user nor a developer, so I'll refrain from advocating a particular choice. But I think that the choice of license should depend on what one hopes to attain.

What are your goals here?

GPL and variants thereof have been useful in the past for helping downstream users of corporate-adopted software maintain their rights. It's quite possible that we would not have WebKit today if KHTML had been MIT-licensed instead of LGPL, for instance. However, with more and more software being centralized, the GPL is perhaps less useful than in the past, because running a network service doesn't trigger the "source follows modified versions" clause. Proof assistants seem amenable to this model, so if your goal with copyleft is to keep someone from making a proprietary RedPRL fork that deprives its users of their rights, then AGPL might be worth considering.

Copyleft licenses have been a problem in the past for people working in environments that are too suspicious of them. I've heard stories of idiotic corporate environments where they couldn't install ghc-mod on their machines because there was a corporate policy against copyleft, for instance. So a copyleft license might get in the way of workers who want to use RedPRL, but are prevented from doing so. If your goal is that anyone should be able to use it, then in our present environment, copyleft might not be a good idea.

When I do a license choice, I typically look at the community I'm in, and try to reduce it being a pain. So Pudding is LGPL because that's what Racket is, idris-mode is GPL because it builds on other things from other Emacs modes that are GPL, and my Idris bits are typically BSD like Idris. I suppose there aren't the same kinds of community norms to work with here, though.

**Comment by jonsterling** [comment]
Thanks David for the feedback and information! Also thanks to others who have contacted me personally to provide their opinions. 

I think I would like to holf off on making a decision here for the time being, but will leave this ticket open so that people may continue posting their opinions and feedback. I am inclined at the moment to make no change to the existing license, but am open to it if there is sufficient reason.
