### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by ak3n** [RedPRL/sml-redprl#95]
I have started implementing interactive mode (#94) and want to discuss how to do it properly.

How do I see it:
1. Editor runs redprl in interactive mode and communicates with it by using stdin and stdout (may be replaced later).
2. Interactive mode (IM) loads files and builds ABT with additional info (source maps). So we need to build a mapping between source code and ABTs: each node will have a pair (offset, length). How to do it with ABTs?
3. When we edit some line in Atom (e.g.), our plugin sends a message like {"cmd": "change", "filename": "proof.prl", "offset": 12, "value": "..."}.
4. IM gets this message and changes ABT according to new value (don't know how to do it).
5. Atom plugin tracks user's cursor and IM analyses what can suggested (tactics, names, etc).

What do you think? 

For more clear description please check out [this paper](http://hillside.net/plop/2013/papers/Group2/plop13_preprint_22.pdf).

/cc @jonsterling, @freebroccolo

**Comment by freebroccolo** [comment]
What you describe sounds reasonably straightforward to do at least on the Atom side of things. I'll have to read the paper though.

As I see it, there are two separate aspects of an interactive mode here.

1. how to synchronize the state between the runtime and the editor/server
2. how to present the state to the editor in a manner that facilitates interaction

I have mostly been considering (2) because I don't know enough about the internals anymore to have a good idea of how (1) should go yet.

My suggestion regarding (2) is that rather than focusing on building our own new protocol specific to Atom/Emacs/whatever, maybe we should try to take advantage of some pre-existing stuff. In particular, I think it would be very interesting to make a [jupyter](https://jupyter.org/) kernel for RedPRL. Jupyter is what used to be called IPython, but which has now been generalized to support a large number of other languages.

Using Jupyter would have a number of advantages. For starters, it would remove a lot of the need to worry about designing the communication backend. It would also allow us to take advantage of a lot of existing software. In particular, there is a very slick Atom mode called [Hydrogen](https://atom.io/packages/hydrogen) that we could use. We could build some custom widgets for our use case but otherwise it would be fairly standard.

**Comment by freebroccolo** [comment]
Here's a [reference](https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernels) for how to implement Jupyter kernels.

**Comment by jonsterling** [comment]
regarding source positions, we may need to add supoort tonthe abt lib.

**Comment by freebroccolo** [comment]
One complication with the jupyter approach is that it uses zeromq. This is fine, but using zeromq from SML is going to be difficult. It looks like KC has a zeromq package for MLton [here](https://github.com/kayceesrk/mlton-zmq) but it has not been updated in quite awhile and may not work with the current library and protocol.

Rather than trying to get that to work, I think it would be much easier to just write a wrapper with Node that handles the zmq messaging and pipes to stdin/stdout. In fact, with this approach, there may not need to be any significant changes to RedPRL to support some interactive mode. The wrapper could handle invocation of RedPRL as a short running child process as needed.

**Comment by jonsterling** [comment]
could definitely make sense to try and do zmq stuff via node (in flow perhaps); for the experimental, non-core aspects of redprl, I think we should use whatever tools make the task easiest, rather than SML dogmatism (we use SML exclusively for the core to ensure code longevity).

**Comment by freebroccolo** [comment]
Yeah, another advantage to using node/flow for that part is that it could just be made another dependency of the Atom mode so the user wouldn't have to worry about setting up a server component or doing some sort of manual configuration or anything like that. Same goes for other editors that could use node like VS Code. If there is a need for something higher performance or native for some part of it, it's really easy to use Rust to build native node modules. These can be shipped pre-compiled for the various platforms.

**Comment by gabriel-fallen** [comment]
> IM gets this message and changes ABT according to new value (don't know how to do it).

Why do you think just re-reading the whole file wouldn't work?
I'd rather tried this simpler approach first and only after encountering problems (like too slow re-reading) introduced complications of (possibly inconsistent) patching of pre-built ABT.

Does it make sense?

**Comment by ak3n** [comment]
@freebroccolo Hydrogen looks amazing! 

@gabriel-fallen Because if the source code is incorrect parser will return not a new ABT, but error message. Our ABT in memory is outdated and we don't know what's wrong with source code (we can't suggest edits e.g.) and it's slow, yes.

I will take a look on Jupyter the next weekend.

**Comment by gabriel-fallen** [comment]
@ak3n I suspect most of the time you're going to start with incorrect (empty) source file so ABT-patching isn't going to solve all the problems. Are there any examples of satisfactory solutions for parsing partial files for other languages?

For what I heard IntelliJ IDEA teams develop custom parsers for supported languages capable of handling partial and incorrect files. But that's double work.

**Comment by jonsterling** [comment]
I don't think I want to rely on anything that would require partial parsing to work, since we are trying to simplify our parsing apparatus at the same time. :)

**Comment by ak3n** [comment]
Okay, I got a working solution with Pexpect based on [bash_kernel](https://github.com/takluyver/bash_kernel) (stdin, stdout).

The problem is that stdin is limited. It means that cells with a lot of code just break kernel.

What we can do:

- Forbid big cells, let user to split them himself.
- Split code in cell and send by chunks.
- Try to implement a more stable server with ZeroMQ support instead of this wrapper.

Is this wrapper enough for now? And how to add a state for signatures? Since we want to remember a result of executed code.

**Comment by jonsterling** [comment]
Regarding states for signatures, can you elaborate a bit on what you need? For instance, I've added all thus json coding stuff for signatures so that we can dump a state to a file and restore it, without having to re-run the proofs; I don't know if this has anything to do with what you need though...

**Comment by ak3n** [comment]
@jonsterling  IPython runs code in cells and they share state. We need the same behaviour, to use results of other cells.
<img width="199" alt="screen shot 2016-08-07 at 20 56 02" src="https://cloud.githubusercontent.com/assets/588373/17463536/64a0c708-5ce1-11e6-9906-86ca31d84ef7.png">

I think that we can use JSON for that.

**Comment by favonia** [comment]
I wonder what is the current state of this? Apparently the "reading-the-whole-file" method is reaching its limit (in a good way).
